name: Release

on:
  push:
    tags:
      - v*

jobs:
  build-binaries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: x86_64-unknown-linux-musl
      - name: Install musl
        run: sudo apt-get install musl-tools
      - name: cargo build --release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-unknown-linux-musl
      - name: strip
        run: strip 'target/x86_64-unknown-linux-musl/release/homebins'
      - name: Get version
        id: version
        shell: bash
        run: |
          VERSION="$(cargo pkgid | cut -d'#' -f2 | cut -d: -f2)"
          echo "::set-output name=version::$VERSION"
          echo "::set-output name=tag::v$VERSION"
      - name: Build package
        id: package
        shell: bash
        run: |
          ARCHIVE_NAME="homebins-${{ steps.version.outputs.tag }}-x86_64-unknown-linux-musl"
          ARCHIVE_FILE="${ARCHIVE_NAME}.tar.gz"
          mkdir "/tmp/${ARCHIVE_NAME}"
          cp README.md CHANGELOG.md LICENSE "target/x86_64-unknown-linux-musl/release/homebins" "/tmp/${ARCHIVE_NAME}"
          tar -czf "${PWD}/${ARCHIVE_FILE}" -C /tmp/ "${ARCHIVE_NAME}"
          echo ::set-output "name=file::${ARCHIVE_FILE}"
          echo ::set-output "name=name::${ARCHIVE_NAME}.tar.gz"
      - name: Upload archive
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.package.outputs.name }}
          path: ${{ steps.package.outputs.file }}
      - name: Upload raw binary
        uses: actions/upload-artifact@v2
        with:
          name: homebins
          path: target/x86_64-unknown-linux-musl/release/homebins

  create-release:
    runs-on: ubuntu-latest
    needs: build-binaries
    steps:
      - uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v4.1.7
        with:
          path: ./artifacts
      - name: Aggregate assets
        run: |
          mkdir ./assets
          mv ./artifacts/*/*.tar.gz ./artifacts/homebins/homebins ./assets
      - name: Compute checksums
        # We create checksum files in the parent directory to avoid checksumming the checksums
        run: |
          b2sum * > ../B2SUMS.txt
          sha512sum * > ../SHA512SUM.txt
          mv ../B2SUMS.txt ../SHA512SUM.txt .
        working-directory: assets
      - name: Get version
        id: version
        shell: bash
        run: |
          VERSION="$(cargo pkgid | cut -d'#' -f2 | cut -d: -f2)"
          echo "::set-output name=version::$VERSION"
      - name: Extract changelog
        shell: bash
        run: |
          awk -v r='${{ steps.version.outputs.version }}' \
            '/^\[[^]]*\]/{print $0}/^## \[[0-9]/ && match($0, /\[[0-9][^]]*\]/){if (r == substr($0, RSTART+1, RLENGTH-2)) { p=1; next } else { p=0 } }p' \
            CHANGELOG.md > ./CHANGELOG-release.md
          cat CHANGELOG-release.md
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ steps.version.outputs.version }}
          body_path: ./CHANGELOG-release.md
          files: "./assets/*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
